"""Derive calibration coefficients from the full reference set.

Runs the production StrainAnalyzer pipeline on every reference compound,
pairs the resulting raw MMFF94 strain with the literature value, and
fits per-ring-size linear coefficients ``(a, b)`` such that
``a * raw + b ≈ exp``. Writes the result to
``ring_strain/calibration_coefficients.json`` so that subsequent loads
of ``StrainCalibrator`` are instant.

Usage::

    python -m scripts.derive_calibration

Expected runtime: ~10-15 min (each substituted reference takes ~30-90 s).
Idempotent: rerun any time the reference set changes.
"""

import json
import sys
import time
from pathlib import Path
from typing import Dict, List, Tuple

# Run from project root: `python scripts/derive_calibration.py`.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ring_strain.core import StrainAnalyzer
from ring_strain.calibrate import _fit_size_coefficients


OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "ring_strain"
    / "calibration_coefficients.json"
)


def main() -> int:
    analyzer = StrainAnalyzer()
    db = analyzer.ref_db

    # Bucket (raw, exp) pairs by ring size across the reference set.
    size_pairs: Dict[int, List[Tuple[float, float]]] = {}
    per_ref_info: List[Dict] = []

    t_start = time.time()
    refs = db.get_all()
    print(f"Deriving calibration from {len(refs)} references...")
    for i, ref in enumerate(refs, 1):
        # Only monocyclic saturated carbocycles are supported by the
        # current pipeline. The reference DB is already curated for this
        # but we skip defensively.
        if ref.ring_count != 1:
            continue
        size = ref.ring_sizes[0]
        t0 = time.time()
        try:
            report = analyzer.analyze(ref.smiles)
        except Exception as exc:
            print(f"  [{i}/{len(refs)}] {ref.name}: FAILED ({exc})")
            continue
        if not report.is_supported:
            print(f"  [{i}/{len(refs)}] {ref.name}: unsupported ({report.validation_message})")
            continue
        raw = report.total_strain_mmff_kcal_mol
        exp = ref.strain_energy_kcal_mol
        size_pairs.setdefault(size, []).append((raw, exp))
        per_ref_info.append({
            "name": ref.name,
            "smiles": ref.smiles,
            "ring_size": size,
            "raw": raw,
            "exp": exp,
        })
        dt = time.time() - t0
        print(
            f"  [{i}/{len(refs)}] {ref.name}: size={size} "
            f"raw={raw:+.2f} exp={exp:+.2f} ({dt:.1f}s)"
        )

    # Fit per size.
    size_coeffs: Dict[str, Dict[str, float]] = {}
    print("\nFitted coefficients (a*raw + b = exp):")
    for size in sorted(size_pairs.keys()):
        pts = size_pairs[size]
        a, b = _fit_size_coefficients(pts)
        size_coeffs[str(size)] = {
            "a": round(a, 6),
            "b": round(b, 6),
            "n_points": len(pts),
        }
        print(f"  size={size}: a={a:+.4f} b={b:+.4f} (n={len(pts)})")

    payload = {
        "method": "linear_per_size",
        "comment": (
            "Generated by scripts/derive_calibration.py. "
            "calibrated = a[size] * raw + b[size]"
        ),
        "size_coeffs": size_coeffs,
        "data_points": per_ref_info,
    }

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as fp:
        json.dump(payload, fp, indent=2)

    total_dt = time.time() - t_start
    print(f"\nWrote {OUTPUT_PATH} in {total_dt:.1f}s.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
